# Generated by Django 3.2.13 on 2022-07-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220717_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.CharField(choices=[('MAN', 'Man'), ('WOMAN', 'Woman'), ('CHILD', 'Child'), ('TEENAGER', 'Teenager'), ('SUMMER', 'Summer'), ('WINTER', 'Winter')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
