# Generated by Django 3.2.13 on 2022-08-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220807_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(default='', upload_to='media'),
        ),
    ]
